### ISSUE TITLE
Bug - Text in input is invisible until clicked on

### ISSUE THREAD

**Issue by deepakduggirala** [IUSCA/bioloop#146]
<img width="650" alt="image" src="https://github.com/IUSCA/bioloop/assets/1618149/ab7f1b09-1be4-4124-a40b-e64b7006027c">

<img width="576" alt="image" src="https://github.com/IUSCA/bioloop/assets/1618149/81b274ac-ac91-4fb7-9afd-d3c4b8fb24da">

**Comment by ri-pandey** [comment]
Merged to dev. Awaiting testing in Bioloop's dev instance.
