### ISSUE TITLE
Allow users to initiate a stage dataset request

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/bioloop#161]
In CPA, a researcher (user) was trying to stage a dataset that was only on tape. For 2022_08_163_Shahbazi – Reza says it is giving him the error ‘unable to stage’. 

As an administrator, I was able to initiate the stage. I suspect this is a permission issue and that users are not able to initiate a stage request from the portal.   

https://cpa.sca.iu.edu/projects/raw-files-for-reza-2024

**Comment by deepakduggirala** [comment]
Fixed in 09fc4a18c1b609164c14e9879fb337c9ff237afa

Added access controls to let users with user role launch "stage" workflow on only datasets that they can access through project associations.
