### ISSUE TITLE
File Browser layout - file list exceeding beyond footer

### ISSUE THREAD

**Issue by ri-pandey** [IUSCA/bioloop#178]
When the list of files in the File Browser exceeds the footer, the file list overflows beyond the footer. Ideally, vertical scroll should kick into effect in such situations.

<img width="1508" alt="Screenshot 2024-02-27 at 8 06 45 PM" src="https://github.com/IUSCA/bioloop/assets/96927993/fdb33827-7e10-44fa-a29b-6478efb48bac">

**Comment by deepakduggirala** [comment]
fixed https://github.com/IUSCA/bioloop/pull/191
