### ISSUE TITLE
Provide a way to see full dataset name in DatasetSelect component

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/bioloop#212]
When attempting to add or remove datasets to a project using the DatasetSelect component, it's difficult to distinguish between datasets if they share a common prefix (e.g. '2024_01_31_Pi' in the screenshot below):
 
![Screenshot from 2024-04-05 12-46-31](https://github.com/IUSCA/bioloop/assets/2225624/4189ece4-2910-44f1-a461-4cb3cde9759d)

I know there is a lot of information being displayed in a small context, so the truncated version of the name is necessary. One idea would be to show a tool tip on mouse hover that includes the full name of the dataset.

**Comment by charlesbrandt** [comment]
We should also expand the default number of characters to show in the name to be longer than 13 (or what it's currently set to). There is even room in the current layout to accommodate the additional characters. Trying to disambiguate between different datasets becomes impossible with a common prefix:
![image](https://github.com/IUSCA/bioloop/assets/2225624/6e424e2d-24b4-436a-8be4-15a1f7fd4862)

**Comment by ri-pandey** [comment]
Tested in dev, merged to main. Ready for release.
