### ISSUE TITLE
Allow About page to be editable

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/bioloop#77]
Currently, the About page requires changes via code. Operators or Admins should have the ability to change the content on the About page directly via the portal. The editor should accept basic markdown syntax, and the corresponding markdown content should be stored in the database. 

![image](https://github.com/IUSCA/bioloop/assets/2225624/879bfbb3-ae4d-4569-9619-33f6636993eb)

**Comment by ri-pandey** [comment]
Release notes:

Run script `src/api/prisma/seed_data/102/populate_about.js` after release to Prod, which will populate the base About text in the database. The base About text is hardcoded in this script, and will need to be updated based on the instance of Bioloop being released.

Instructions:

```
sudo docker compose -f "docker-compose-prod.yml" exec api bash
(inside api container) node prisma/seed_data/102/populate_about.js
```
