### ISSUE TITLE
Implement "Upload" feature

### ISSUE THREAD

**Issue by charlesbrandt** [IUSCA/bioloop#99]
Occasionally data products are generated outside of a given instance of Bioloop. In this situation, operators need a way to manually import or ingest the data product. 

In CMG, we call this process uploading, however it is more similar to ingesting from a custom path:

![image](https://github.com/IUSCA/bioloop/assets/2225624/f50d2e08-5be1-4f88-80d2-b1852c5cb2b8)

If the operator derived the data product from an existing dataset (raw data source) that already exists in the data portal, there should be a way to associate the data product being uploaded with the source dataset. 

@ryanlong89 has also implemented related functionality in the context of NGVB that successfully manages transferring large data from the operator's local machine to the server. @ryanlong89 , could you add a pointer to that functionality here? 

@ri-pandey , once you've had a chance to review existing solutions, please document and describe the approach you plan to take to implement the feature here in this issue (before starting actual development). 

FYI @deepakduggirala

**Comment by ri-pandey** [comment]
Release notes:

1. Add these properties to api/.env:
```
OAUTH_UPLOAD_CLIENT_ID=example
OAUTH_UPLOAD_CLIENT_SECRET=example
UPLOAD_PATH=/path/to/upload/dir
DOWNLOAD_DIR_RELATIVE_PATH=/path
```
2. Add these properties to secure_download's api/.env:
```
UPLOAD_PATH_DATA_PRODUCTS=/path/to/uploaded/data_products
```
3. Add these to ui/.env:
```
UPLOAD_API_BASE_PATH=https://localhost
```
